server:
  port: 9200
spring:
  application:
    name: user-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.242.137:3306/lagou_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.242.137
    port: 6379
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
auth:
  ttl: 3600
  clientId: lagou
  clientSecret: lagou
  cookieDomain: .lagou.com
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/lagou.jks   #私钥路径
    secret: edu.lagou   #密钥 加盐
    alias: lagou        #证书别名 生成证书指定的
    password: edu.lagou   #访问私钥的密码
